apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: async-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: 753086500241.dkr.ecr.us-east-1.amazonaws.com/async-pipeline-worker:latest
          command: ["celery", "-A", "config", "worker", "--loglevel=info", "--pool=solo"]
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: pipeline-config
            - secretRef:
                name: pipeline-secrets