apiVersion: apps/v1
kind: Deployment
metadata:
  name: beat
  namespace: async-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beat
  template:
    metadata:
      labels:
        app: beat
    spec:
      containers:
        - name: beat
          image: 753086500241.dkr.ecr.us-east-1.amazonaws.com/async-pipeline-beat:latest
          command: ["celery", "-A", "config", "beat", "--loglevel=info"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
          envFrom:
            - configMapRef:
                name: pipeline-config
            - secretRef:
                name: pipeline-secrets