apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  namespace: async-pipeline
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: 753086500241.dkr.ecr.us-east-1.amazonaws.com/async-pipeline-web:latest
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - configMapRef:
                name: pipeline-config
            - secretRef:
                name: pipeline-secrets