apiVersion: v1
kind: Secret
metadata:
  name: pipeline-secrets
  namespace: async-pipeline
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "jkz1d7we_(78d@wmylv+l)a4=in783gq)t81$$enau!sfq(gehl"
  POSTGRES_PASSWORD: "pipeline"