apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
  namespace: async-pipeline
data:
  DJANGO_DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "*"
  POSTGRES_DB: "pipeline"
  POSTGRES_USER: "pipeline"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  CELERY_BROKER_URL: "redis://redis:6379/0"