apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: async-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: async-task-pipeline-worker:latest
          imagePullPolicy: IfNotPresent
          command: ["celery", "-A", "config", "worker", "--loglevel=info", "--pool=solo"]
          envFrom:
            - configMapRef:
                name: pipeline-config
            - secretRef:
                name: pipeline-secrets