apiVersion: apps/v1
kind: Deployment
metadata:
  name: beat
  namespace: async-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beat
  template:
    metadata:
      labels:
        app: beat
    spec:
      containers:
        - name: beat
          image: async-task-pipeline-beat:latest
          imagePullPolicy: IfNotPresent
          command: ["celery", "-A", "config", "beat", "--loglevel=info"]
          envFrom:
            - configMapRef:
                name: pipeline-config
            - secretRef:
                name: pipeline-secrets